### ISSUE TITLE
Implement documentation for components as a Launcher/Nerdlet

### ISSUE THREAD

**Issue by tangollama** [newrelic/nr1-community#14]
- Listing of components on the left
- Rendered code
- Code snippet + documentation

**Comment by danielgolden** [comment]
Here's [a prototype of the design for the docs](https://www.figma.com/proto/YAkXjlXfvOZaWaKtIEQynq/NR1-Community?node-id=1%3A1372&viewport=-306%2C237%2C0.8856343030929565&scaling=contain) (be sure to scroll).

**Comment by devfreddy** [comment]
**To Do's**
- [x] Make side-navigation into component and hide
- [x] Remove readme, but add link to it

**Post-poning**
- [ ] Now that we've detached the readme contents, setup ReactVisibilitySensor to work with sidenav

**Comment by danielgolden** [comment]
Added link for readme: 1b1cd827eac10ea6bf2692daf198e950aa2d0a94
