### ISSUE TITLE
Rename EventStream to EventTimeline or other

### ISSUE THREAD

**Issue by Kav91** [newrelic/nr1-community#29]
Given we have a nerdpack called "Event Stream" already https://github.com/newrelic/nr1-event-stream

I think this component should be better named to Timeline since it is clearly a time based component, more-so then offering any streaming capabilities itself.

Also to avoid any confusion with an already used name within the same programmability ecosystem.

**Comment by devfreddy** [comment]
The original form of this one was Event-driven so it made sense at the time, but not anymore. It was originally called `<Timeline>` and I believe we changed it, for a specific project, to avoid confusion with another timeline-like component. 

We've altered it to be more generic, the component's only real expectation is that you will provide it with at least one timestamp field + format for display.

We're thinking and acting on a change to make it `<Timeline>` as that best represents its purpose.

Thanks for pointing this out @Kav91
