### ISSUE TITLE
Account Picker

### ISSUE THREAD

**Issue by devfreddy** [newrelic/nr1-community#3]
See conversation in https://github.com/newrelic/open-source-office-private/issues/3

**Comment by tangollama** [comment]
Make use of https://developer.newrelic.com/client-side-sdk/index.html#data-fetching/AccountsQuery

**Comment by devfreddy** [comment]
Initial add - fba84fb54b91143dc89cab97a8d3ee50629a9ad5 derived in part from nr1-commune

Initially adding Lew's more advanced AccountDropdown - 856018bfe72af49e2d70532de45e97dec4683630, 9e02d60681c8c60967a4500ed5e3b5b42efa90cc

Adding an onError callback - 9aa9413e252f2ee056406c7ba420a518ca782ec9

This one's ready for some testing and/or iteration from a design/usability perspective.
i.e.
- Does it work in it's current form enough to ship it?
- What else would be useful to add to this component?

**Comment by danielgolden** [comment]
Tested the `AccountPicker` component to make sure it works as we say it does and ran into a few issues:
- It looks like the markdown parser is omitting the numbers of our order lists (see the installation section)
- When I paste in the snippet for the component `<AccountDropdown></AccountDropdown>`  and hit save, it reduces it to `<AccountDropdown />` (not sure if this is really a problem or not).
- Pasting in the provided styles snippet at the top of a .scss file seems to break/remove all styles from the page. I don't think the provided path is correct. `@import '~nr1-community/dist/index.css';`
- ~I'm going to add a "label" prop to this component so users can add their own label~ - Done: b3a6ab0.
- After going through the steps of using the account dropdown I'm not sure how to get it running.
- When I follow each step the only thing I get is a dropdown with "no account found..." inside.

**Comment by devfreddy** [comment]
> It looks like the markdown parser is omitting the numbers of our order lists (see the installation section)

I'll look into this

> When I paste in the snippet for the component <AccountDropdown></AccountDropdown> and hit save, it reduces it to <AccountDropdown /> (not sure if this is really a problem or not).

This is just ESLint noticing you haven't provided any props so it simplifies it down

> After going through the steps of using the account dropdown I'm not sure how to get it running.

This definitely could use some work - I'll add something for this

> When I follow each step the only thing I get is a dropdown with "no account found..." inside.

Let's take a look at this.

**Comment by danielgolden** [comment]
Removing this component from the project: #28.
