### ISSUE TITLE
so how can I take a try of nr1 cli?

### ISSUE THREAD

**Issue by wulucxy** [newrelic/nr1-community#54]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

I can not find any document about how to get a try of nr1 cli, does it have any cummunity version?

**Comment by danielgolden** [comment]
Hi, @wulucxy. If you are already a customer of New Relic then you can use the NR1 CLI by loggin into New Relic and following the instructions on [this page](https://one.newrelic.com/launcher/developer-center.launcher). 

If you are not a customer of New Relic, you can still use the NR1 CLI for free by signing up for our [Developer Edition](https://developer.newrelic.com/build-tools/new-relic-one-applications/developer-edition-program).
