### ISSUE TITLE
Standard graphql-apollo-style Error component

### ISSUE THREAD

**Issue by tangollama** [newrelic/nr1-community#8]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

Create a standard error output component to deal with the GraphQL output in the data fetching interface.

```
({ loading, error, data}) => {
  if (error) {
    return <StandardErrorComponent error={error} />
  }
}
```

[NOTE]: # ( Provide a brief overview of what the new feature is all about. )

**Comment by tangollama** [comment]
- Provide a prop that allows you to show the details on the error automatically. Otherwise, click to see it
- Provide a formatting function for the details

**Comment by devfreddy** [comment]
1. What do we think of `<NerdGraphError>` as the component name? We could expand and have a similar `<NrqlError>` component.

2. Should we make an effort to pass in and show the original GraphQL query as well? Could get big and gnarly if we attempt to show this + the stack trace but something for consideration

@danielgolden @tangollama
