### ISSUE TITLE
Standard Detail Panel

### ISSUE THREAD

**Issue by tangollama** [newrelic/nr1-community#9]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

Create standard markup/styling for a detail panel. https://user-images.githubusercontent.com/812989/66426047-0907dd80-e9df-11e9-9315-fa5092180765.png

**Comment by danielgolden** [comment]
a1262ef

**Comment by danielgolden** [comment]
This needs to be tested
